name: jestAction
on: [push]
jobs:
  jest-run:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Install dependencies
        run: npm install
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.4
        with:
          working-directory: ./
